# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/powerpack/all/powerpack.rbi
#
# powerpack-0.1.2
class Array
  def butfirst; end
end
module Enumerable
  def drop_last(n); end
end
class Hash
  def symbolize_keys; end
end
class String
  def blank?; end
  def strip_indent; end
end
