module Rubanok
  module DSL
    module Mapping : Processor
      class Rule < Rubanok::Rule
        METHOD_PREFIX: String

        private
        def build_method_name: () -> String
      end

      module ClassMethods : Module, _RulesAdding
        def map: (*field fields, ?activate_on: (field | Array[field]), ?activate_always: bool, ?ignore_empty_values: bool, ?filter_with: Symbol) { () -> input } -> void
      end

      def self.included: (singleton(Processor) base) -> void
    end
  end
end
