module Rubanok
  module DSL
    module Mapping
      class Rule < Rubanok::Rule
        METHOD_PREFIX: String

        private
        def build_method_name: () -> String
      end

      module ClassMethods
        def map: (*field fields, ?activate_on: (field | Array[field]) activate_on, ?activate_always: bool activate_always, ?ignore_empty_values: bool ignore_empty_values, ?filter_with: Method? filter_with) { () -> input } -> void
      end

      def self.included: (singleton(Processor) base) -> void
    end
  end
end
