module Rubanok
  class UnexpectedInputError < StandardError
  end

  module DSL
    module Matching : _Processor
      class Rule < Rubanok::Rule
        METHOD_PREFIX: String
        @method_name: String
        @fields: Array[field]

        class Clause < Rubanok::Rule
          @fields: Array[field]

          attr_reader values: params
          attr_reader id: String
          attr_reader block: ^() -> input

          def initialize: (String id, Array[field] fields, untyped values, ?activate_on: field | Array[field], ?activate_always: bool) { () -> input } -> void
          def applicable?: (params) -> bool

          alias to_method_name id
        end

        attr_reader clauses: Array[Clause]

        def matching_clause: (hash params) -> Clause?
        def having: (*untyped values) { () -> input } -> void
        def default: () { () -> input } -> void

        private
        def build_method_name: () -> String
      end

      def default_match_handler: (Rule rule, hash params, bool? fail_when_no_matches) -> void

      module ClassMethods : Module, _RulesAdding
        def match: (*field fields, ?activate_on: field | Array[field], ?activate_always: bool, ?fail_when_no_matches: bool?) { (Rule) -> void } -> void
        def define_method: (String | Symbol) ?{ () [self: Rubanok::Processor] -> void } -> Symbol
      end
    end
  end
end
