module Rubanok
  def self.fail_when_no_matches: () -> bool
  def self.fail_when_no_matches=: (bool) -> bool
  def self.ignore_empty_values: () -> bool
  def self.ignore_empty_values=: (bool) -> bool
end
