module Rubanok
  def self.fail_when_no_matches: () -> untyped
  def self.fail_when_no_matches=: (untyped) -> untyped
  def self.ignore_empty_values: () -> untyped
  def self.ignore_empty_values=: (untyped) -> untyped
end
