# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_2; end
module ActionMailer::Base::Mail::Message; end
module RSpec::Rails::ControllerExampleGroup; end
