name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.4"]
        gemfile: ["gemfiles/rails8.gemfile"]
        rbs: ["true"]
        include:
        - ruby: "2.7"
          gemfile: "gemfiles/rails6.gemfile"
          rbs: "false"
        - ruby: "3.0"
          gemfile: "gemfiles/rails70.gemfile"
          rbs: "false"
        - ruby: "3.3"
          gemfile: "gemfiles/rails7.gemfile"
          rbs: "false"
        - ruby: "3.2"
          gemfile: "gemfiles/railsmaster.gemfile"
          rbs: "false"
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec
      run: |
        bundle exec rspec
    - name: Run RSpec with RBS
      if: matrix.rbs == 'rbs'
      run: |
        bundle exec rake spec:rbs -- --force-color
